# Generated by Django 3.2.7 on 2021-09-14 09:07

from django.db import migrations, models


def create_roles(apps, schema_editor):
    """
    Creates the default roles
    Args:
        apps():
        schema_editor():
    Returns:
        None
    """

    roles = apps.get_model("users", "Role")
    name_code_list = [
        ("Customer", "CU"),
        ("Content Manager", "CM"),
        ("System Admin", "SA"),
        ("Sales Manager", "SM"),
    ]
    for role in name_code_list:
        name, code = role
        roles(name=name, code=code).save()


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=30, unique=True)),
                ("code", models.CharField(max_length=2, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RunPython(create_roles),
    ]
