# Generated by Django 3.2.7 on 2021-09-10 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_auto_20210910_0717"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Active/Inactive status of a user"
            ),
        ),
    ]
