# Generated by Django 3.2.7 on 2021-09-17 12:36

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0003_auto_20210917_1128"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="total_bill",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                max_digits=20,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Total Payable",
            ),
        ),
    ]
