# Generated by Django 3.2.7 on 2021-09-15 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("price", models.IntegerField(verbose_name="Product Price")),
                ("quantity", models.IntegerField(verbose_name="Product Quantity")),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=1000, verbose_name="Product Description"
                    ),
                ),
                ("price_unit", models.CharField(max_length=3, verbose_name="Currency")),
                ("name", models.CharField(max_length=100, verbose_name="Product Name")),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
