# Generated by Django 3.2.7 on 2021-10-01 00:48

from django.db import migrations, models

import products.utils


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=products.utils.image_path
            ),
        ),
    ]
