# Generated by Django 3.2.7 on 2021-09-29 09:11

from django.db import migrations, models

import products.utils


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                default="product_image.png",
                null=True,
                upload_to=products.utils.image_path,
            ),
        ),
    ]
