# Generated by Django 3.2.7 on 2021-09-17 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_product_created_by"),
        ("products", "0002_auto_20210917_1028"),
    ]

    operations = []
